# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: HiFi electronices store
# Description of the Site
description: HiFi will be used to browse and purchase the latest electronics and computer parts with the best deals.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.discordapp.com/attachments/1085773515690627132/1095074662943301804/hero_icon.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: bianfengfan@gmail.com
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: HIFIdeveloper

# Name of the Author
author-name: TheHiFi
# URL for the Image of the Author
author-image: https://cdn.discordapp.com/attachments/1085773515690627132/1095074662943301804/hero_icon.jpg
# 60 Words About the Author
author-about: "HiFi - your ultimate destination for electronic devices. Intended for customers who want to use technology to make live easier. Whether you're need everyday items or household or work items, our wide range of products is tailored to meet your needs. From smartphones and laptops to gaming consoles and smart home devices, we have everything you need to stay connected and stay ahead. So come explore our online store and discover products to make your live easier with HiFi."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/fyfe-c

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
# permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
